# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql/mysql-server
    # command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: c1vG7R34
      MYSQL_DATABASE: samsmk3
      MYSQL_USER: digitalman
      MYSQL_PASSWORD: c1vG7R34
      TZ: Asia/Kuala_Lumpur
    ports:
      - "3306:3306"
volumes:
  db_data:
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080