# FROM node:14.20.0-alpine 
# 14.20.0-alpine works fine on DOCKER host memory 39MB
FROM node:16.16.0-alpine
# 16.16.0-alpine works fine on DOCKER host memory 40.7MB
# create destination directory
RUN mkdir -p /usr/src/nuxt-app
WORKDIR /usr/src/nuxt-app

# update and install dependency
RUN apk update && apk upgrade
RUN apk add git

# copy the app, note .dockerignore
COPY . /usr/src/nuxt-app/
RUN npm install
RUN npm run build

EXPOSE 3000

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

CMD [ "npm", "start" ]
